### ISSUE TITLE
Fehlermeldung beim Filtern auf Tags.

### ISSUE THREAD

**Issue by tniebergall** [MetaModels/filter_tags#12]
In folgendem Aufbau bekomme die unten stehende Fehlermeldung.

Ich habe 2 mehrsprachige MetaModels "Einsatzbereich" und "Produkte"
Einsatzbereich wird in Produkte mittels eines Tag Attributes referenziert.
In Produkte habe ich einen Filter Mehrfachauswahl auf das Tag Attribut.
Wähle ich nun im Frontend eine Option erhalte ich folgende Fehlermeldung.

```
Fatal error: Uncaught exception Exception with message Query error: Unknown column 'alias' in 'where clause' (SELECT id FROM mm_application WHERE alias IN ('garten')) thrown in system/modules/core/library/Contao/Database/Statement.php on line 293
#0 system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->query()
#1 system/modules/metamodelsattribute_tags/classes/src/MetaModels/Filter/Rules/FilterRuleTags.php(86): Contao\Database\Statement->execute(Array)
#2 system/modules/metamodelsattribute_tags/classes/src/MetaModels/Filter/Rules/FilterRuleTags.php(101): MetaModels\Filter\Rules\FilterRuleTags->sanitizeValue()
#3 system/modules/metamodelsattribute_tags/classes/src/MetaModels/Attribute/Tags/AbstractTags.php(246): MetaModels\Filter\Rules\FilterRuleTags->getMatchingIds()
#4 system/modules/metamodels/classes/src/MetaModels/Filter/Rules/SearchAttribute.php(81): MetaModels\Attribute\Tags\AbstractTags->searchFor('garten')
#5 system/modules/metamodels/classes/src/MetaModels/Filter/Filter.php(113): MetaModels\Filter\Rules\SearchAttribute->getMatchingIds()
#6 system/modules/metamodels/classes/src/MetaModels/Filter/Rules/Condition/ConditionOr.php(99): MetaModels\Filter\Filter->getMatchingIds()
#7 system/modules/metamodels/classes/src/MetaModels/Filter/Filter.php(113): MetaModels\Filter\Rules\Condition\ConditionOr->getMatchingIds()
#8 system/modules/metamodels/classes/src/MetaModels/Filter/Setting/Collection.php(196): MetaModels\Filter\Filter->getMatchingIds()
#9 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/FrontendFilter.php(291): MetaModels\Filter\Setting\Collection->getParameterFilterWidgets(Array, Array, Object(MetaModels\FrontendIntegration\FrontendFilterOptions))
#10 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/FrontendFilter.php(79): MetaModels\FrontendIntegration\FrontendFilter->getFilters()
#11 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/HybridFilterBlock.php(130): MetaModels\FrontendIntegration\FrontendFilter->getMetaModelFrontendFilter(Object(MetaModels\FrontendIntegration\Content\Filter))
#12 system/modules/core/classes/Hybrid.php(219): MetaModels\FrontendIntegration\HybridFilterBlock->compile()
#13 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(99): Contao\Hybrid->generate()
#14 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/HybridFilterBlock.php(119): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#15 system/modules/core/library/Contao/Controller.php(469): MetaModels\FrontendIntegration\HybridFilterBlock->generate()
#16 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#17 system/modules/core/modules/Module.php(154): Contao\ModuleArticle->compile()
#18 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
#19 system/modules/core/library/Contao/Controller.php(405): Contao\ModuleArticle->generate(false)
#20 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), true, false, 'main')
#21 system/modules/core/pages/PageRegular.php(129): Contao\Controller::getFrontendModule('0', 'main')
#22 system/modules/core/controllers/FrontendIndex.php(244): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#23 index.php(20): Contao\FrontendIndex->run()
#24 {main}
```

**Comment by discordier** [comment]
Existiert denn ein alias attribut im Einsatzbereich?

**Comment by tniebergall** [comment]
Ja ist vorhanden, allerdings ein tanslatedalias.

**Comment by tniebergall** [comment]
Hab es mal testweise auf einen normalen alias umgestellt, dann geht es. Also fehlt anscheinend die Abfrage für einen translatedalias.

Wenn ein Testzugang hilfreich wäre einfach melden, dann richte ich was ein.

**Comment by xantippe** [comment]
@tniebergall tritt der Fehler noch auf? bei den Multilanguage-Attributen hatte sich einiges getan...

**Comment by tniebergall** [comment]
@xantippe müsste ich mal bei Gelegenheit testen.

**Comment by xantippe** [comment]
was wäre prima

**Comment by tniebergall** [comment]
@xantippe der Fehler ist behoben.
